<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Taala Crystal V2 Sales Data Report</title>
    <style>
        @page {
            margin: 28px 32px;
        }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #18313f;
        }

        h1 {
            margin: 0 0 4px;
            font-size: 20px;
            color: #0b4f78;
        }

        h2 {
            margin: 18px 0 8px;
            font-size: 14px;
            color: #2d8796;
        }

        .muted {
            color: #667b84;
        }

        .header {
            border-bottom: 3px solid #2d8796;
            padding-bottom: 10px;
            margin-bottom: 14px;
        }

        .company {
            font-size: 10px;
            color: #667b84;
            margin-bottom: 6px;
        }

        .range {
            margin-top: 4px;
        }

        .summary-table,
        .breakdown-table {
            width: 100%;
            border-collapse: collapse;
        }

        .summary-table td {
            width: 20%;
            border: 1px solid #d6e6ea;
            padding: 8px;
            vertical-align: top;
        }

        .summary-label {
            display: block;
            color: #667b84;
            font-size: 9px;
            margin-bottom: 4px;
        }

        .summary-value {
            font-size: 13px;
            font-weight: bold;
        }

        .breakdown-table th,
        .breakdown-table td {
            border: 1px solid #d6e6ea;
            padding: 6px 7px;
        }

        .breakdown-table th {
            background: #eaf6f8;
            color: #174f63;
            text-align: left;
        }

        .text-right {
            text-align: right;
        }

        .empty {
            text-align: center;
            color: #777;
            padding: 18px;
        }

        .footer-note {
            margin-top: 16px;
            font-size: 9px;
            color: #667b84;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Taala Crystal</h1>
        <div class="company">Uholo Fresh Springs Co. Ltd | P.O. Box 277-40606, Ugunja | +254 724 293 226 | uholofreshsprings@gmail.com</div>
        <div><strong>V2 Sales Data Report</strong></div>
        <div class="range muted">
            Date range:
            {{ filled($filters['date_from'] ?? null) ? $filters['date_from'] : 'Beginning' }}
            to
            {{ filled($filters['date_to'] ?? null) ? $filters['date_to'] : 'Latest' }}
        </div>
        <div class="muted">Completed V2 sales only. Draft sales are excluded.</div>
    </div>

    <table class="summary-table">
        <tr>
            <td>
                <span class="summary-label">Completed Sales</span>
                <span class="summary-value">{{ number_format((int) $summary->completed_sales_count) }}</span>
            </td>
            <td>
                <span class="summary-label">Total Sales Value</span>
                <span class="summary-value">KES {{ number_format((float) $summary->total_sales_value, 2) }}</span>
            </td>
            <td>
                <span class="summary-label">Total Units Sold</span>
                <span class="summary-value">{{ number_format($totalUnitsSold, 0) }}</span>
            </td>
            <td>
                <span class="summary-label">Walk-in Sales</span>
                <span class="summary-value">KES {{ number_format((float) $summary->walk_in_total, 2) }}</span>
            </td>
            <td>
                <span class="summary-label">Business Sales</span>
                <span class="summary-value">KES {{ number_format((float) $summary->business_total, 2) }}</span>
            </td>
        </tr>
    </table>

    <h2>Product Sales Breakdown</h2>

    <table class="breakdown-table">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Finished Product</th>
                <th class="text-right">Units Sold</th>
                <th class="text-right">Sales Value</th>
            </tr>
        </thead>
        <tbody>
            @forelse($productBreakdown as $product)
                <tr>
                    <td>{{ $product->sku }}</td>
                    <td>{{ $product->name }}</td>
                    <td class="text-right">{{ number_format((float) $product->units_sold, 0) }}</td>
                    <td class="text-right">KES {{ number_format((float) $product->sales_value, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="empty">No completed V2 sales exist for the selected date range.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer-note">
        Generated by Taala Crystal. This report is derived from completed V2 sales records and their stored historical line totals.
    </div>
</body>
</html>
